// ============================================================
// NEBULA 星环商城 · Mock 商品数据（移植自 quantum 仓库各页面硬编码商品）
// 后端接口不可达/无数据时兜底展示，接真实数据后由 API 返回替换
// ============================================================
import type { ProductCardItem } from '@/components/nebula/ProductCard/index.vue'

export const MOCK_PRODUCTS: ProductCardItem[] = [
  {
    id: 'mock-101',
    name: '全息投影腕带 HX-7 星际版',
    category: 'HOLO-DEVICE',
    icon: '◬',
    tag: '-70%',
    tagType: 'red',
    score: 4.9,
    sales: '2.1w',
    price: 899,
    oldPrice: 2999,
  },
  {
    id: 'mock-102',
    name: '量子计算芯片 Q-9000 双核',
    category: 'QUANTUM-CHIP',
    icon: '◉',
    phClass: 'p2',
    tag: '新品',
    tagType: 'blu',
    score: 5.0,
    sales: '980',
    price: 6499,
    oldPrice: 12999,
  },
  {
    id: 'mock-103',
    name: '机甲外骨骼 EXO-α 助力套装',
    category: 'MECH-EXO',
    icon: '⬡',
    phClass: 'p3',
    tag: '秒杀',
    tagType: 'grn',
    score: 4.8,
    sales: '3.6k',
    price: 3999,
    oldPrice: 8888,
  },
  {
    id: 'mock-104',
    name: '神经链接头盔 N-3 冥想舱',
    category: 'NEURAL-LINK',
    icon: '▣',
    phClass: 'p4',
    tag: '-45%',
    tagType: 'red',
    score: 4.9,
    sales: '8.9k',
    price: 1299,
    oldPrice: 2399,
  },
  {
    id: 'mock-105',
    name: '月球基地户外宇航服 L-2',
    category: 'SPACE-GEAR',
    icon: '◌',
    phClass: 'p2',
    tag: '新品',
    tagType: 'blu',
    score: 4.7,
    sales: '1.2k',
    price: 15999,
    oldPrice: 22800,
  },
  {
    id: 'mock-106',
    name: '便携聚变能源舱 3000W',
    category: 'ENERGY-CELL',
    icon: '⚡',
    tag: '热卖',
    tagType: 'grn',
    score: 4.8,
    sales: '5.4k',
    price: 2499,
    oldPrice: 3999,
  },
  {
    id: 'mock-107',
    name: '桌面全息投影仪 Holo-Desk Pro',
    category: 'HOLO-DEVICE',
    icon: '✺',
    phClass: 'p3',
    tag: '-60%',
    tagType: 'red',
    score: 4.9,
    sales: '12k',
    price: 1799,
    oldPrice: 4499,
  },
  {
    id: 'mock-108',
    name: '视网膜增强义眼 VI-9 夜视版',
    category: 'CYBER-IMPLANT',
    icon: '◈',
    phClass: 'p2',
    tag: '新品',
    tagType: 'blu',
    score: 4.6,
    sales: '734',
    price: 5999,
    oldPrice: 8888,
  },
  {
    id: 'mock-109',
    name: '光子存储阵列 1PB 家庭云',
    category: 'QUANTUM-CHIP',
    icon: '⌬',
    tag: '热卖',
    tagType: 'grn',
    score: 4.9,
    sales: '2.8k',
    price: 4299,
    oldPrice: 6999,
  },
  {
    id: 'mock-110',
    name: '城市巡逻无人机 X-2 自动巡航',
    category: 'DRONE-SYS',
    icon: '◮',
    phClass: 'p4',
    tag: '-35%',
    tagType: 'red',
    score: 4.7,
    sales: '4.6k',
    price: 2899,
    oldPrice: 4499,
  },
  {
    id: 'mock-111',
    name: '地月旅行舱票 · 太空酒店 3 日',
    category: 'SPACE-GEAR',
    icon: '☾',
    phClass: 'p2',
    tag: '新品',
    tagType: 'blu',
    score: 5.0,
    sales: '316',
    price: 88000,
    oldPrice: 120000,
  },
]

// ===== 商品库全量数据（24 件 · 8 大分类 · 6 大品牌，列表页筛选/排序用） =====
export interface ListProduct {
  id: number
  name: string
  cat: string
  brand: string
  price: number
  old: number
  sales: number
  rating: number
  tag: string
  icon: string
  ph: string
  image?: string
  /** 商品属性（颜色/屏幕刷新率等，搜索接口 sku attrs 字段） */
  attrs?: Array<{
    attrId: number | string
    attrName: string
    attrValue: string[]
  }>
}

export const PRODUCTS_LIST: ListProduct[] = [
  // 全息设备
  {
    id: 1,
    name: '全息投影腕带 HX-7 星际版',
    cat: '全息设备',
    brand: 'NEBULA',
    price: 899,
    old: 2999,
    sales: 21000,
    rating: 4.9,
    tag: '特价',
    icon: '◬',
    ph: '',
  },
  {
    id: 2,
    name: '桌面全息投影仪 Holo-Desk Pro',
    cat: '全息设备',
    brand: 'ASTRAL',
    price: 1799,
    old: 4499,
    sales: 12000,
    rating: 4.9,
    tag: '热卖',
    icon: '◫',
    ph: 'p3',
  },
  {
    id: 3,
    name: '全息通讯面罩 Halo-Com S',
    cat: '全息设备',
    brand: 'CYBERION',
    price: 1299,
    old: 1999,
    sales: 5600,
    rating: 4.7,
    tag: '新品',
    icon: '◭',
    ph: 'p2',
  },
  // 量子计算
  {
    id: 4,
    name: '量子计算芯片 Q-9000 双核',
    cat: '量子计算',
    brand: 'QUANTEX',
    price: 6499,
    old: 12999,
    sales: 980,
    rating: 5.0,
    tag: '新品',
    icon: '◉',
    ph: 'p2',
  },
  {
    id: 5,
    name: '光子存储阵列 1PB 家庭云',
    cat: '量子计算',
    brand: 'QUANTEX',
    price: 4299,
    old: 6999,
    sales: 2800,
    rating: 4.9,
    tag: '热卖',
    icon: '⌬',
    ph: '',
  },
  {
    id: 6,
    name: '量子加密路由器 QR-7',
    cat: '量子计算',
    brand: 'NEBULA',
    price: 999,
    old: 1599,
    sales: 4300,
    rating: 4.8,
    tag: '特价',
    icon: '⬡',
    ph: 'p3',
  },
  // 机甲外骨骼
  {
    id: 7,
    name: '机甲外骨骼 EXO-α 助力套装',
    cat: '机甲外骨骼',
    brand: 'CYBERION',
    price: 3999,
    old: 8888,
    sales: 3600,
    rating: 4.8,
    tag: '特价',
    icon: '▣',
    ph: 'p4',
  },
  {
    id: 8,
    name: '外骨骼液压关节 EX-J 升级件',
    cat: '机甲外骨骼',
    brand: 'ORBITLAB',
    price: 1499,
    old: 2299,
    sales: 1900,
    rating: 4.6,
    tag: '',
    icon: '◈',
    ph: '',
  },
  {
    id: 9,
    name: '战术机甲头盔 MK-9',
    cat: '机甲外骨骼',
    brand: 'CYBERION',
    price: 2499,
    old: 3699,
    sales: 1200,
    rating: 4.7,
    tag: '新品',
    icon: '◫',
    ph: 'p2',
  },
  // 神经接口
  {
    id: 10,
    name: '神经链接头盔 N-3 冥想舱',
    cat: '神经接口',
    brand: 'NEBULA',
    price: 1299,
    old: 2399,
    sales: 8900,
    rating: 4.9,
    tag: '热卖',
    icon: '▣',
    ph: 'p4',
  },
  {
    id: 11,
    name: '脑波传感耳机 Wave-2',
    cat: '神经接口',
    brand: 'VOLTAIC',
    price: 699,
    old: 999,
    sales: 6700,
    rating: 4.8,
    tag: '特价',
    icon: '◌',
    ph: 'p2',
  },
  {
    id: 12,
    name: '神经反馈训练舱 NT-1',
    cat: '神经接口',
    brand: 'QUANTEX',
    price: 8999,
    old: 12999,
    sales: 420,
    rating: 4.9,
    tag: '会员',
    icon: '✺',
    ph: '',
  },
  // 智能义体
  {
    id: 13,
    name: '视网膜增强义眼 VI-9 夜视版',
    cat: '智能义体',
    brand: 'ORBITLAB',
    price: 5999,
    old: 8888,
    sales: 734,
    rating: 4.6,
    tag: '新品',
    icon: '◉',
    ph: 'p2',
  },
  {
    id: 14,
    name: '仿生义肢臂 A-7 全地形',
    cat: '智能义体',
    brand: 'CYBERION',
    price: 7999,
    old: 11999,
    sales: 610,
    rating: 4.7,
    tag: '会员',
    icon: '☾',
    ph: 'p3',
  },
  {
    id: 15,
    name: '皮下健康芯片 H-1',
    cat: '智能义体',
    brand: 'VOLTAIC',
    price: 1999,
    old: 2999,
    sales: 2300,
    rating: 4.8,
    tag: '热卖',
    icon: '◈',
    ph: '',
  },
  // 太空装备
  {
    id: 16,
    name: '月球基地户外宇航服 L-2',
    cat: '太空装备',
    brand: 'ASTRAL',
    price: 15999,
    old: 22800,
    sales: 1200,
    rating: 4.7,
    tag: '新品',
    icon: '◌',
    ph: 'p2',
  },
  {
    id: 17,
    name: '地月旅行舱票 · 太空酒店 3 日',
    cat: '太空装备',
    brand: 'ORBITLAB',
    price: 88000,
    old: 120000,
    sales: 316,
    rating: 5.0,
    tag: '会员',
    icon: '☾',
    ph: 'p2',
  },
  {
    id: 18,
    name: '轨道舱重力靴 G-Boots',
    cat: '太空装备',
    brand: 'ASTRAL',
    price: 3499,
    old: 4999,
    sales: 880,
    rating: 4.6,
    tag: '特价',
    icon: '◮',
    ph: 'p4',
  },
  // 能量补给
  {
    id: 19,
    name: '便携聚变能源舱 3000W',
    cat: '能量补给',
    brand: 'VOLTAIC',
    price: 2499,
    old: 3999,
    sales: 5400,
    rating: 4.8,
    tag: '热卖',
    icon: '⚡',
    ph: '',
  },
  {
    id: 20,
    name: '反物质电池组 AB-50',
    cat: '能量补给',
    brand: 'VOLTAIC',
    price: 599,
    old: 899,
    sales: 9800,
    rating: 4.7,
    tag: '特价',
    icon: '⚡',
    ph: 'p3',
  },
  {
    id: 21,
    name: '太阳能帆板套件 Solar-4',
    cat: '能量补给',
    brand: 'ASTRAL',
    price: 1599,
    old: 2599,
    sales: 2100,
    rating: 4.5,
    tag: '',
    icon: '✧',
    ph: '',
  },
  // 无人机
  {
    id: 22,
    name: '城市巡逻无人机 X-2 自动巡航',
    cat: '无人机',
    brand: 'NEBULA',
    price: 2899,
    old: 4499,
    sales: 4600,
    rating: 4.7,
    tag: '热卖',
    icon: '◮',
    ph: 'p4',
  },
  {
    id: 23,
    name: '星际侦察无人机 Recon-1',
    cat: '无人机',
    brand: 'ORBITLAB',
    price: 4599,
    old: 6999,
    sales: 1500,
    rating: 4.8,
    tag: '新品',
    icon: '▽',
    ph: 'p2',
  },
  {
    id: 24,
    name: '物流运输无人机 Cargo-D8',
    cat: '无人机',
    brand: 'CYBERION',
    price: 7999,
    old: 10999,
    sales: 720,
    rating: 4.6,
    tag: '会员',
    icon: '◬',
    ph: '',
  },
]
