/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackground: typeof import('./components/nebula/AppBackground/index.vue')['default']
    AppFeatures: typeof import('./components/nebula/AppFeatures/index.vue')['default']
    AppFooter: typeof import('./components/nebula/AppFooter/index.vue')['default']
    AppHeader: typeof import('./components/nebula/AppHeader/index.vue')['default']
    AppNav: typeof import('./components/nebula/AppNav/index.vue')['default']
    AppPromo: typeof import('./components/nebula/AppPromo/index.vue')['default']
    ConfirmDialog: typeof import('./components/nebula/ConfirmDialog/index.vue')['default']
    PageSearchHeader: typeof import('./components/nebula/PageSearchHeader/index.vue')['default']
    ProductCard: typeof import('./components/nebula/ProductCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Ticker: typeof import('./components/nebula/Ticker/index.vue')['default']
  }
}
